name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    permissions:
      contents: read
      pull-requests: read
    uses: global-torque/.github/.github/workflows/public-package-ci.yml@55fd65234263c3990f176b179070d5cddc260c68
    with:
      install-browser: true
